import "./globals.css";

import { ThirdwebProvider } from "@/providers/ThirdWebProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import SideBar from "@/components/sidebar/SideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThirdwebProvider
          activeChain="mumbai"
          clientId={process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
        >
          <ThemeProvider>
            <div className="min-h-screen relative">
              <SideBar />
              <div className="ml-56 w-[calc(100vw-14rem)] ">{children}</div>
            </div>
          </ThemeProvider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
